name: Release

permissions:
  contents: write

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
    steps:
      - name: set git global safe directory
        run: |
          pacman -Syu git npm --noconfirm
          git config --global --add safe.directory $(realpath .)

      - uses: actions/checkout@v4

      - name: submodules
        run: |
          git submodule update --init --recursive py_modules

      - name: change log level
        run: |
          sed -i 's/logging.DEBUG/logging.INFO/' py_modules/config.py

      - name: build plugin
        run: |
          npm i -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm update @decky/ui --latest
          pnpm update @decky/api --latest
          pnpm run build
          # tar -czvf huesync.tar.gz --transform 's,^,HueSync/,' dist backend py_modules *.py *.json *.md *.js LICENSE
          temp_dir=$(mktemp -d)
          mkdir -p $temp_dir/HueSync
          cp -r dist backend py_modules *.py *.json *.md *.js LICENSE $temp_dir/HueSync
          tar -czvf huesync.tar.gz -C $temp_dir HueSync
      
      - name: show files
        run: |
          tar -tzvf huesync.tar.gz
      
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: huesync
          path: huesync.tar.gz

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/artifacts/huesync/huesync.tar.gz
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: contains(github.ref, 'pre') || contains(github.ref, '.rc')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}